services:

  web:
    container_name: sksk_ko_python
    build:
      dockerfile: ./app/Dockerfile
    env_file: .env.prod
    restart: always
    volumes:
      - .:/workspace
    ports:
      - "9001:8000"
    command: gunicorn -b 0.0.0.0:8000 wsgi:app