DEBUG = True
SESSION_COKKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = True

SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_ECHO = True

NAVER_CLIENT_ID = 'fake'
NAVER_CLIENT_SECRET = 'fake'

GOOGLE_APPLICATION_CREDENTIALS = 'fake'

TESTING = False
